### ISSUE TITLE
Theme refactor Frontend: Page Title Block

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#13]
- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme.
- [x] confirm feature parity 

Estimate: 2

**Comment by markconroy** [comment]
Some notes so far:

1. Template has been moved from localgov_core/templates to theme
2. Template HTML is rewritten so we don't have a `.header` class, which should be reserved for the `<header>` element.
3. Instead the title now has a BEM name class of `.lgd-page-title-block__title`, however our default `h1` styling is enough, so this should only be needed for sub-themes.
3. The "subheader" now has a BEM name class of `.lgd-page-title-block__subheader` in case a sub-theme needs it
4. Our theme is not using this class as we have a utility `.h3` class created which substitutes perfectly

**Comment by danchamp** [comment]
@markconroy 

https://github.com/localgovdrupal/localgov_base/blob/d4c0e1afd5b22a6ef0146948d46564df7270c8e4/templates/block/localgov-page-header-block.html.twig#L23

I like the idea of using `<hgroup>` here but sadly it's been [removed from the HTML5 spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup) since no AT supports it, and advice is not to use it.

So a plain `<div>` is probably the most appropriate container element in all cases?

Otherwise all good for me.

**Comment by markconroy** [comment]
Thanks @danchamp 

Based on this - https://www.w3.org/TR/html52/common-idioms-without-dedicated-elements.html#common-idioms-without-dedicated-elements - it looks like `<header>` might be the best element to use, but I reckon that's only if the title was inside the `<article>` element, not using the block system we are using. 

In the meantime, I've gone for `<div>`

**Comment by danchamp** [comment]
@markconroy Agreed, if the page title block could be wrangled into the `<article>` element for some content types that would be ideal, but I know that's a bigger issue than we can deal with here.
