### ISSUE TITLE
Theme refactor frontend: localgov_services_landing_page

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#14]
# Sample page: http://localgov.dev.mark.ie/births-deaths-marriages-and-citizenship

- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme.
- [x] confirm feature parity

Estimate: 13

**Comment by markconroy** [comment]
Update 1:

- Contact Section is now complete
- The contact section is now NOT using font-awesome as an imported library, instead we just embed the SVGs inline - this removes over 1MB of downloads from an external resource.
![Screenshot 2021-06-01 at 12 52 01](https://user-images.githubusercontent.com/2183332/120318803-32722d00-c2d8-11eb-9488-19e7873da1f0.jpg)

**Comment by markconroy** [comment]
Update 2:
- Layout for the Service Landing Page is complete.
- This layout uses our custom `.lgd-row` grid system, rather than bootstrap. it's very lightweight, and based on the GovUK design system.
![Screenshot 2021-06-01 at 12 53 30](https://user-images.githubusercontent.com/2183332/120318973-64838f00-c2d8-11eb-9d5b-777504344450.jpg)

**Comment by markconroy** [comment]
Update 3:
- Layout for service CTA block is complete
- This layout uses our lgd-row classes
- No bootstrap
- No font awesome

![Screenshot 2021-06-01 at 16 07 49](https://user-images.githubusercontent.com/2183332/120346732-8b02f380-c2f3-11eb-880d-360ef5f25f94.jpg)

**Comment by markconroy** [comment]
I think this is ready to test now. Files to consider:

- `block/services-cta-block.html.twig`
- - This templaet adds the CTA links to the top of the service landing page
- - Note use of new way to include icons
- `includes/icons/icon.html.twig`
- - new way to include icons without loading the whole of font awesome
- - `content/node--localgov-services-landing--full.html.twig`
- - this is a _very_ custom template for the services landing page. Hopefully other templates will be more generic
- `content/node--teaser.html.twig`
- - This template is for the teaser view mode for services listed on the service landing page
- `field/field--node--localgov-destinations--localgov-services-landing.html.twig`
- - This template lists services at the top of service landing page
- - Note this is the template that adds the icon to the teaser (at a field level instead of a node level)

**Comment by cjstevens78** [comment]
@markconroy i think something may have gone awry with the example page for this - most likely to do with another element like the service status - or perhaps some work you are doing for hiding the right hand column anyway its currently showing the 'popular topics' (right hand) column next to the 'contact' area - i think from your screenshots above it should be next to the services list .... so other than that I noticed a couple of things:

- originally the list of services was spread over 3 cols in a full width container - the right hand column had been removed.  
- Services list has `<h3>` headers but there's no preceding '<h2>' - this may just be to do with the page being out of sorts
- ‘slp__contact-list’ is indented by 40px

**Comment by markconroy** [comment]
Thanks @cjstevens78 

1. I think the "Popular Topics" are right where they are. I followed the general HTML order of the current theme, which you can see here - http://localgov-test.dev.mark.ie/births-deaths-marriages-and-citizenship
2. Should we add the 3col container back to the services list?
3. The teasers are using h3 as their main element. I guess we can easily add a title of `<h2>Services</h2>` above it, so we have the correct hierarchy?
4. Contact list indenting is now removed

**Comment by msayoung** [comment]
@markconroy can we have an aria label of some sort for the CTA nav please?
Gotta go now, but I'll continue reviewing tomorrow.

**Comment by markconroy** [comment]
@msayoung That's done now.

**Comment by msayoung** [comment]
Questions today:
Are the Read more links on the service updates invisible on purpose? 

![image](https://user-images.githubusercontent.com/3852805/122382182-9431c880-cf61-11eb-9710-f5811b2875ea.png)

This may not be the place to raise this, but what do you think about adding some visually hidden text to anywhere we have "Read more" links so that they are more informative? eg Read more <span class="visually-hidden"> about {{ node.title }} </span>

Do we want the phone number as a phone link?

**Comment by msayoung** [comment]
@markconroy - also are we going for the 3-across layout for the subpages lists, as we have on the current theme? 
Currently we have 1 per row http://localgov.dev.mark.ie/adult-health-and-social-care

**Comment by markconroy** [comment]
@msayoung The "Service Updates" is not part of this work. I'll do that in a separate PR. I didn't do it originally as it's a different content type and the HTML was changing.

**Comment by willguv** [comment]
I would leave the service updates panel at the foot of the landing page for now. I'm speaking to Brighton about their use of it, and we can return to this later.

**Comment by andybroomfield** [comment]
Just to ask, would the Service Update content type and the field to turn service updates on be removed.
It is still used at BHCC, even if its not the best place for it it should still be possible to in order to aide adoption.
So if it is a feature LocalgovDrupal supports then the new theme should support it to
(and if it is being dropped, that has big implications for Brighton & Hoves adoption plans).

**Comment by willguv** [comment]
No decisions have been made about this Andy. I’d like to leave the re-theming work of the service updates panel until later as I need to hear from Nikki about its use in Brighton. I’ll send both her and Chloe a reminder email today and copy you in.

**Comment by willguv** [comment]
@markconroy ignore me. I'm not able to meet with Brighton & Hove until 7th July, so we need to include the service update styling on the service landing page as it is currently styled

If there are any changes I'll write cards at a late date

Copying @andybroomfield

**Comment by danchamp** [comment]
@markconroy Edge case contrast issue when hovering over a focussed service CTA link:

<img width="406" alt="Screenshot 2021-06-22 at 15 29 07" src="https://user-images.githubusercontent.com/261421/122943317-d3e81e00-d36e-11eb-9bfe-26d46221339f.png">

Caused by `color` not being explicitly declared for `.sctab__link:hover` in [service-cta-block.css](https://github.com/localgovdrupal/localgov_base/blob/1.x/css/components/service-cta-block.css#L21-L24)

**Comment by danchamp** [comment]
> This may not be the place to raise this, but what do you think about adding some visually hidden text to anywhere we have "Read more" links so that they are more informative? eg Read more about {{ node.title }}

@msayoung +1 on this, since the link text isn't under editorial control and if there are multiple statuses on a service page they all currently have the same **Read more** link text.

[In step-by-step](https://github.com/localgovdrupal/localgov_step_by_step/blob/8a85f388479313a21e40ceee443c1db5633079ad/templates/views-view-list--localgov-step-by-step-navigation--prev-next.html.twig#L56
) we used `aria-label` rather than visually hidden text - not sure there's any benefit either way, but we might want to be consistent in the approach?

**Comment by danchamp** [comment]
I think a heading of 'Address' would be helpful above the postal address where it's present, otherwise it's not always going to be clear to a screen reader user what that content is:

<img width="666" alt="Screenshot 2021-06-22 at 16 09 26" src="https://user-images.githubusercontent.com/261421/122950489-663ef080-d374-11eb-8e18-c1f0bc88c6c6.png">

Possibly move the icon next to 'View map' too, so all lines of the address are left aligned and the link matches the email link pattern?

**Comment by danchamp** [comment]
@markconroy That's all I've got, other than those bits it's all great for me.

**Comment by markconroy** [comment]
@danchamp Thanks a lot. All updated now.

@msayoung Adding more meaningful text is bigger than just this content type, so I have created a new issue for it where we can tackle it all in one go https://github.com/localgovdrupal/localgov_base/issues/60

**Comment by danchamp** [comment]
Thanks @markconroy, this is good for me.
