### ISSUE TITLE
Support theme option in subsites

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_base#192]
On a subsite overview page, a content editor can select a Visual theme option. 

This value was designed to be passed as a class to the page template, but we are currently not printing this in the page.html.twig

`Lines 119 - 144 https://github.com/localgovdrupal/localgov_subsites/blob/2.x/localgov_subsites.module`
So to get this working we need to add something like `{{ attributes.addClass(classes) }}` to the page.html.twig

However - this doesn't wrap the banner region so perhaps we want it on the `<body>` tag instead? 
@markconroy  do you have any thoughts? 

once we've decided that, It would be good to demo the choice of visual themes for subsites in Scarfolk or the base theme. Maybe a quick and dirty dark theme? 

```
.theme--b {
  background: white;
  filter: invert(100%);
}

.theme--b img {
 filter: invert(100%);
}
```

**Comment by msayoung** [comment]
@markconroy remind me why the {{ page.banner }} ended up outside of the `<main> `

Inherited from the old theme?

**Comment by markconroy** [comment]
The {{ page.banner }} (if I remember correctly) is outside `<main>` (presuming that's what's missing in your comment above!!!) because of the general site structure - the need for the breadcrumbs coming after the banner.

I guess we could add a theme setting to place the banner after breadcrumbs and vice versa. Then a simple conditional in the page.html.twig file for where to render it.

I wasn't aware of https://github.com/localgovdrupal/localgov_subsites/blob/2.x/localgov_subsites.module#L119 to allow a new value in the theme. We can fix that, I'm sure. But ... in our default set up, the only value we have is "default". Do we want to add options for theme 1, theme 2, theme 3, etc? And ... should this be a taxonomy field, so each site can easily add the number of themes they want, rather than use giving fixed values and content designers wondering why theme 4 doesn't work on their site? We could have a theme setting for the taxonomy id for each theme.

**Comment by markconroy** [comment]
@maria I am going close this issue.

I think the **Subsites Extras** module gives us this functionality. Feel free to re-open if you think we need to work on this.
