### ISSUE TITLE
Theme Refactor: Guide Overview

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#20]
# Sample: http://localgov.dev.mark.ie/adult-health-and-social-care/travel-passes-and-support/blue-badges

- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme.
- [x] confirm feature parity

**Comment by markconroy** [comment]
This is ready for review. Files to consider include:

- `block/guides-contents-block.html.twig`
- - This is the block at the top of the page which gives the listing of guide pages
- `content/node--localgov-guides-overview--full.html.twig`
- - Full node template for a guide overview page.
- - the main point of this seems to be to add the word "Overview" into the template in a `h2`. Maybe we could come up with a simpler way.

**Comment by cjstevens78** [comment]
- In AXE there’s an ‘all elements must be contained within a landmark’ warning involving the page title area https://github.com/localgovdrupal/localgov_base/blob/master/templates/block/localgov-page-header-block.html.twig. It’s tricky because you can’t simply wrap it in a `<header>` tag because there’s already one being used for the actual header. After some faffing we went with adding an aria role of ‘complimentary’ to the container. This got rid of the error - not sure if it fully resolves the issue though. https://github.com/localgovdrupal/localgov_theme_croydon/commit/87c3a99edd59c0d2d02d989268eecd9a318dcf31

- We spoke in the meeting about the dashes used in the sub nav here - IMO they should be removed. A numbered or bulleted list is native and expected by a user.

- The grid layout seems a bit off, left right margins causing misalignment. See screenshot.

- I notice the ‘Next’ button on this page has the class of ‘lgd-prev-next__list-item--prev’ which means it’ll pick up any ‘previous’ button styling instead of ‘next’

![overview-screen-grid](https://user-images.githubusercontent.com/11304107/121880242-b0392e00-cd05-11eb-87d8-79596f4b9f0b.png)

**Comment by cjstevens78** [comment]
Also - the list of items in the sub navigation all have the class 'lgd-guide-nav__list-item--active' this will mean they all inherit and active state styling - I would have thought there would be one 'active' link to denote the page you are on.

**Comment by markconroy** [comment]
Thanks @cjstevens78 

1. Axe/Header - I'm going to skirt around that if you don't mind. I think where the page title block is placed currently - outside of the flow of the `<article>` element is not correct, but we'll need a wider discussion about how to fix that. It's not even inside the `<main>` element, which is a big mistake I think.
2. I'll leave the dashes styling there for now, just so it actually works for any sites that are using it. But we should make an effort to have it removed.
3. Well spotted on the grid layout, that should be fixed now.
4. Well spotted on those `--prev` and `--active` classes. Both should be fixed now as well.

**Comment by msayoung** [comment]
Great. 

Can we have a name for the nav region please?

**Comment by markconroy** [comment]
@msayoung do you mean something like `<nav name="guide-nav"></nav>`?

**Comment by msayoung** [comment]
Sorry @markconroy , I meant a label. Something like
```
<nav aria-labelledby="heading-id">
<h2 id="heading-id" class="visually-hidden">Guide Navigation</h2> ...
</nav>
```
Or an aria-label if that's simpler.

**Comment by markconroy** [comment]
I've gone with `aria-label`. We don't seem to have access to the parent block from this template (or it's a block inside a block, I'm not sure).

**Comment by danchamp** [comment]
Looks good @markconroy, thanks.

The use of 'navigation' in the `aria-label` is redundant - screen readers will announce the role, so will read 'Guide navigation navigation'.

> I've gone with `aria-label`. We don't seem to have access to the parent block from this template (or it's a block inside a block, I'm not sure).

We can easily make the guide title available to the block as a variable if it would improve it - not sure 'Blue badges navigation' is an improvement over 'Guide navigation' in this context though?

**Comment by markconroy** [comment]
Thanks @danchamp that word is removed now.
