### ISSUE TITLE
Inline field label

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_base#225]
Our inline field labels don't display currently display inline. 

IE
If i set a field's label to display inline in Manage Display

**Comment by mccrodp** [comment]
Hey @msayoung or @markconroy, could we get some clearer details here. eg.

1. a screenshot or 
1. steps to reproduce this including the links to any screens affected

Otherwise let's close it if no longer relevant? Currently looking at `good first issue` tickets that I might grab. Cheers!

**Comment by markconroy** [comment]
I think this was fixed by Justine last year. Here's the [PR](https://github.com/localgovdrupal/localgov_base/pull/503)

However, that CSS could be made a bit more modern. I think these lines:
```
.field--label-inline .field__label,
.field--label-inline .field__items {
  float: left; /* LTR */
}
```
are problematic, even though we copied them from Classy. It means any nested fields that have field label above if they are inside a field with label inline will not place the labels above.

We could also rewrite the padding-left/right using logical properties and remove the [rtl] stuff. I'll create an issue.

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
