### ISSUE TITLE
Theme Re-factor IA-Block

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#25]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components

- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme
- [x] confirm feature parity (we actually have more features, given our new CSS)

![Screenshot 2021-06-15 at 11 29 54](https://user-images.githubusercontent.com/2183332/122037984-0a50f680-cdcd-11eb-8dd0-95f8f5ea0313.jpg)

**Comment by markconroy** [comment]
Branch 1.x

Ready for review.

Files to consider:
- `paragraphs/paragraph--localgov-ia-block.html.twig` - template file
- `css/components/ia-block.css`
- - `css/components/ia-block.ie11.css`

**Comment by danchamp** [comment]
Looks good @markconroy 

Only issue I can see is the focus style for linked headings in IA blocks being very subtle and inconsistent with all other link focus styling.

Caused by the `<div>` from `content.localgov_ia_block_title` rendered inside the anchor:

https://github.com/localgovdrupal/localgov_base/blob/0d10381e84b34297494bc8074b8375ec021a6063/templates/paragraphs/paragraph--localgov-ia-block.html.twig#L63

**Comment by markconroy** [comment]
Thanks @danchamp 

That should be fixed now if you want to give it another quick check.

**Comment by danchamp** [comment]
All good @markconroy, thanks.

**Comment by msayoung** [comment]
looks great
