### ISSUE TITLE
Theme Re-factor: Link and Summary

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#27]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components/test-page-link-and-summary-component

- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme
- [x] confirm feature parity

**Comment by markconroy** [comment]
See PR https://github.com/localgovdrupal/localgov_base/pull/29

**Comment by msayoung** [comment]
is the icon meant to be vertically aligned with the title @markconroy ?  (and can it be? :) )
![image](https://user-images.githubusercontent.com/3852805/122557486-c2340d00-d034-11eb-9fcc-12c1ce978d2e.png)

**Comment by markconroy** [comment]
@msayoung Sorry, I gave you the link to my default test site, not my dev site. I've corrected that now.

**Comment by danchamp** [comment]
@markconroy We could improve this with an `aria-describedby` attribute on the link, referencing the summary.

The link would then be announced somthing like:

> Link. The blog of LGD. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a...

Otherwise users consuming the content linearly (eg screen reader) will not have access to the context provided by the summary when encountering the link.

**Comment by markconroy** [comment]
Thanks Dan, that's added now.
