### ISSUE TITLE
using the localgov-page-section template for page-sections

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_base#314]
In https://github.com/localgovdrupal/localgov_base/pull/291 we added paragraph--page-section.html to use the same template as the new localgov_page_section 

Remind me why we wanted to do this @markconroy ? 

I've got some broken layouts which i suspect I can fix, but just wanted to check the motivation.

**Comment by markconroy** [comment]
I can't remember explicitly. But I think it had something to do with localgov_page_section needing one template, but if others create the same funcationality (since we are not providing an update hook to get this funcationality) then they will need paragraph--page-section template.

I could be wrong, but I think it's something like that.

**Comment by markconroy** [comment]
@msayoung shall we close this issue?

**Comment by markconroy** [comment]
I'm going to close this as it doesn't seem to have been raised as an issue again. 

Re-open if needed.
