### ISSUE TITLE
Theme Re-factor: Key Contact Paragraph Type

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#32]
# Sample: http://localgov.dev.mark.ie/test-subsite-demo-all-components/video-page-key-contact

[x] Put the templates in place in the theme
[x] Move styling into localgov_base theme - none needed
[x] confirm feature parity

**Comment by markconroy** [comment]
See PR: https://github.com/localgovdrupal/localgov_base/pull/33

**Comment by danchamp** [comment]
@markconroy I'm finding this hard to review without context of where it would be used, and from that what the purpose of the image might be and what the text alternative should communicate.

The examples I've found on Croydon's subsites where it might have been used seem not to be using it, e.g the Get in touch section here:

https://www.croydon.gov.uk/croydon-needs-foster-carers/find-out-more-about-fostering

Is this the sort of context where it's intended to be used? (This is probably a question for localgov_subsites rather than here.)

My only general observation would be that the presentation is inconsistent with services contacts, where we use icons for email and other elements.

**Comment by msayoung** [comment]
Here's another similar example from Croydon maybe: https://www.croydon.gov.uk/wedding-and-civil-partnership-venues/approved-ceremony-venues-croydon

I've crawled though Lambeth's Bereavement Subsite and can't find anything that looks like the thing, though there are places they could have used it : https://beta.lambeth.gov.uk/bereavement-services

I've asked in one of the Slack channels for real examples.

**Comment by danchamp** [comment]
> Here's another similar example from Croydon maybe: https://www.croydon.gov.uk/wedding-and-civil-partnership-venues/approved-ceremony-venues-croydon

@msayoung That's the sort of use case I'd expect to find, but the Key Contact paragraph type only has fields for a link and an email address - no postal address or phone number.

I wonder if it's legacy/redundant, or unused because it's so limited?

**Comment by msayoung** [comment]
good question if we get to do some targeted user testing on subsites (which I think would be a great idea).
