### ISSUE TITLE
Link guide prev/next to the guide content

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#416]
At the moment when you click on prev/next for a guide, it directs to that guide page, with focus at the top of the page.

Should we link to the `lgd-guides__inner` section instead so you are brought to the next "section" of the guide rather than the next "page" of the guide?

**Comment by keelanfh** [comment]
It *sounds* sensible to me, but I don't know - it would be interesting to know how this fits with users' expectations.

Two related thoughts:
* Would it make sense to do that on the links in the guide navigation as well?
* Should we have a link to skip past the guide navigation? I notice that gov.uk does this on guide pages ([example](https://www.gov.uk/child-benefit/what-youll-get)) - though I'm not sure their wording is the best:
![image](https://user-images.githubusercontent.com/19519457/226938061-49e72f68-3ad1-48b4-980b-c772b1d74e81.png)

@helencalderon any thoughts on this? Would be interesting to see if this comes up with our testing with visually impaired users?

**Comment by keelanfh** [comment]
OK so I said I wasn't sure of users' expectations on this one - since then, we've done a round of usability testing with screenreader users. They generally expected to be taken to the content inside the guide when using the guide navigation, rather than having it repeated.

Though it's less strong evidence, I've also seen on Hotjar screen recordings from mobile devices some quite long delays in scrolling down past the guide contents, which suggests a bit of a struggle here.

So I'd be in favour of changing this, both for the guide contents and the previous/next buttons.
