### ISSUE TITLE
Skipped heading level in service landing pages

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#417]
Our service landing page has a h1, then a listing of teasers which all have h3 for their headings, so we are skipping h2.

Let's put a visually-hidden h2 in place to announce "Services List" or something like that just before the teaser list.

**Comment by keelanfh** [comment]
Related to: https://github.com/localgovdrupal/localgov_services/issues/188

For now on essex.gov.uk we've just changed the teasers to h2s. We do then need to change the news teasers on the homepage to h3s as we've broken the heading order there.

The related PR would introduce an illogical heading order for us because of the change we've made, so we'd have to override this as well. I get that there are tradeoffs here, though.

**Comment by keelanfh** [comment]
Here's what's being worked on for essex.gov.uk - https://github.com/essexcountycouncil/essex-gov-uk-drupal/pull/193, in case of interest - basically duplicating the teaser layout for places where we need h2s.

Still probably leaves some challenges for the service sub-landing pages where there are more ways for the teasers to be used.
