### ISSUE TITLE
Base link :focus style too specific, overrides other styles

### ISSUE THREAD

**Issue by ctorgalson** [localgovdrupal/localgov_base#466]
## Summary

We're finding [the `localgov_base` link focus style `a:not(.toolbar a):focus`](https://github.com/localgovdrupal/localgov_base/blob/1.x/css/base/base.css#L54) unnecessarily difficult to override due to its scope and specificity.

## Explanation

In terms of _scope_, it applies to literally every link in any `localgov_base` child theme that isn't inside `.toolbar` regardless of whether the toolbar is even present. This is confusing and adds a little friction with every link style whose focus doesn't use `localgov_base`'s styles.

In terms of _specificity_, `:not()` has the specificity of its _argument_. This means that the base focus style will override something like `.call-out-box__link:focus` unless we scope it under a parent like `.call-out-box .call-out-box__link:focus` or override the css variable responsible for whatever the problematic property is.

For example, to override the focus background colour on a link, both of these strategies _do_ work:

```css
/* Scoped/descendant selector */
.call-out-box .call-out-box__link:focus {
  background: var(--color-white);
}
```

```css
/* Scoped variable override */
.call-out-box__link:focus {
  --color-focus: var(--color-white);
}
```

## Alternate strategy

Since the `:not()` in the selector is intended to address _only_ links inside `.toolbar`, it should be possible to:

1. change the selector to `.dialog-off-canvas-main-canvas a:focus` (thus targeting virtually everything _but_ `.toolbar`, **or**
2. remove the `:not()` from the selector and add a new rule with the selector `.toolbar a:focus` that specifically un-sets everything that the `a:focus` selector does.

Of the two, I'd suggest (1) since the only non-toolbar link it will miss is `.skip-link` which could be added specifically to the base `:focus` style.

On the other hand, using (2) means `localgov_base` has to take responsibility for the appearance of `.toolbar`, even when Toolbar's own css library changes.

## References:

- https://developer.mozilla.org/en-US/docs/Web/CSS/:not#description
- https://css-tricks.com/almanac/selectors/n/not/#aa-specificity

**Comment by keelanfh** [comment]
## Does this solve the problem?

Doesn't option 1 (`.dialog-off-canvas-main-canvas a:focus`) still override `call-out-box__link:focus`? It still has an extra class. 

![image](https://github.com/localgovdrupal/localgov_base/assets/19519457/e79107a2-a7af-4345-a35f-392a0721798f)

If it helps in some other situations, it seems a reasonable change to make, but I'm not sure I see the value for the problem you're mentioning. I don't really see a way of dropping the specificity below 1 element 2 classes while not interfering with the Toolbar.

## If we do this, can we have a better selector?

The LGD cookie compliance banner is also outside `.dialog-off-canvas-main-canvas`.

Would `a:not(.toolbar):focus` work instead? I think it has equivalent specificity and would also remove interdependency between  us and Toolbar.

## A less specific selector might cause other problems

We did previously have a selector with less specificity (`a:focus`), but that did also have an issue - see e.g. #395.

E.g. in our theme, we have white-on-black links in the footer (I've illustrated with colours here rather than variables for simplicity):

```css
.lgd-footer__pre-footer {
  background-color: black;
}

.lgd-footer__pre-footer a {
  color: white;
}
```

and then the relevant bits of the focus state get applied:

```css
a:focus {
  color: black;
  background-color: yellow;
}
```

which has the end result of:

```css
  color: white;
  background-color: yellow;
```

because `a:focus` is more specific than `.lgd-footer__pre-footer` but is on the same level as `.lgd-footer__pre-footer a` (and set first). This isn't exclusive to this situation, any similar set of selectors will mean that half a focus state is applied. I've seen this 'in the wild' though I can't find an example now. I suppose my concern is that that issue is hard to spot - at least a point of frustration is obvious and you can fix it!

**Comment by ctorgalson** [comment]
> Doesn't option 1 (.dialog-off-canvas-main-canvas a:focus) still override call-out-box__link:focus? It still has an extra class.

Yes! :facepalm: I garbled ways to address two problems into one solution. It'd solve the `:not(.toolbar a)` problem without solving the specificity issue.

> The LGD cookie compliance banner is also outside .dialog-off-canvas-main-canvas.

Sure, but if (if!) the solution of another selector excluding (not negating) children of `.toolbar` worked, this would just mean three selectors for in the base css file instead of one.

> We did previously have a selector with less specificity (a:focus)

I guessed there must have been, but didn't dig for it. IMO, this shows the root problem: `localgov_base` tries to do too much.

My approach in a _base theme_ would be to not even attempt to set colours for a selector as broad as `a:focus`. Setting border, text decoration, outline, even box-shadow all make sense there, but colours vary frequently by component.

Anyway, I'm not suggesting we start over; I think one of your suggestions is about 99% of what's needed:

> Would `a:not(.toolbar):focus` work instead? I think it has equivalent specificity and would also remove interdependency between us and Toolbar.

I don't think that can work, because it isn't the _links_ that have the class `toolbar`: but the links all have classes beginning with `toolbar`. This should be the same specificity, as e.g. `.call-out-box__link`, I think:

```css
a:not([class*="toolbar"]):focus { ... }
```

Demo: https://codepen.io/bedlamhotel/pen/VwVMLBz

This _does_ have the risk of unintentionally hitting links with class names like `/.*toolbar.*/`, but I think that's a smaller problem.

**Comment by keelanfh** [comment]
I'm in favour of your latest proposed change. 🎉

> My approach in a base theme would be to not even attempt to set colours for a selector as broad as a:focus. Setting border, text decoration, outline, even box-shadow all make sense there, but colours vary frequently by component.

I disagree with this. To me, one of the things `localgov_base` should do is make it as easy as possible for councils to create a very accessible theme. The current focus indicator is designed to be highly visible across almost any background and most contexts you use it in. It's not the only way of doing a focus indicator, but it does work.

If we accept that we want to provide a highly visible focus indicator without a requirement for further customisation, then given how many places an `a` link is used, I'm not sure if there's another selector to apply colours to that would be better... but open to ideas on this!

By the way, I love your approach about overriding the `--color-focus` variable. I wouldn't have thought of that as it seems to run counter to my mental model of CSS variables, but it's brilliant.

**Comment by ctorgalson** [comment]
My irrelevant-to-the-issue continuation :)

> I disagree with this. To me, one of the things localgov_base should do is make it as easy as possible for councils to create a very accessible theme.

For this purpose, I think a good pattern is to ship a nice, functional, accessible, but visually un-opinionated base theme _and_ a second theme inheriting from that base to show how a council's specific branding and customizations could be applied. Custom themes could start as a copy of that second theme.

But as I said, I'm not proposing big changes, just thinking out loud.

**Comment by keelanfh** [comment]
> For this purpose, I think a good pattern is to ship a nice, functional, accessible, but visually un-opinionated base theme and a second theme inheriting from that base to show how a council's specific branding and customizations could be applied. Custom themes could start as a copy of that second theme.

Rather than adding a second theme, presumably this would just be a case of moving things to https://github.com/localgovdrupal/localgov_base/tree/1.x/scripts/subtheme-items/css

I guess I'm just not sure how focus states could be accessible without some visual styling... could definitely set some foundations but it would always need some colours added.

**Comment by ctorgalson** [comment]
> Rather than adding a second theme, presumably this would just be a case of moving things

Aha. You've probably guessed that I don't have any very deep grasp of the details here :roll_eyes:.

**Comment by keelanfh** [comment]
> Aha. You've probably guessed that I don't have any very deep grasp of the details here 🙄.

Not at all! I'm just fumbling around here trying to figure things out - you have a much better handle on CSS than me...
