### ISSUE TITLE
Focus effect on a Labelled Icon. 

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_base#555]
In the Subscribe panel paragraph (available on Subsite overview) there are optional Labelled Icons. 

The focus effect only applies to the icon rather than the whole link. 

![image](https://github.com/localgovdrupal/localgov_base/assets/3852805/ccf688e0-5c9b-4437-9b1b-714fa09b8151)

**Comment by markconroy** [comment]
We have 2 issues here (both caused by the same item)

1. The focus style is only applied to the icon, and
2. The label is wrapping to a second line

The reason for both is because we have `<span>`s inside the container (which is correct), but inside the title span we are then rendering the field content which pulls in a field template, which places a `div` inside the span. Being a block-level element, this div is overriding the inline nature of the parent span which causes both of our issues. PR #556 fixes this for us.

![Screenshot 2024-06-06 at 11 22 33](https://github.com/localgovdrupal/localgov_base/assets/2183332/bf35d46e-1177-44e3-a077-ccf19b915e4b)

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
