### ISSUE TITLE
Theme Refactor: Event Content Type

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_base#57]
Recurring Event: http://localgov.dev.mark.ie/events/localgovdrupal-product-group-meetup
Single Event: http://localgov.dev.mark.ie/events/hogmanay-2021

- [x] Put the templates in place in the theme
- [x] Move styling into localgov_base theme.
- [x] confirm feature parity

**Comment by markconroy** [comment]
PR: https://github.com/localgovdrupal/localgov_base/pull/58

**Comment by danchamp** [comment]
@markconroy Using my test event as reference:

![Screenshot 2021-06-24 at 10-49-56 My test event LocalGov Drupal](https://user-images.githubusercontent.com/261421/123242887-5e995c00-d4da-11eb-8ed2-766268d773b8.png)

Not sure if these go beyond 'feature parity':

- Link button styling and hover/focus states are inconsistent with those used in services, guides and step-by-step, and might be better aligned with those?
- Date might need some white-space when there's an image present.
- Geo uses the base field template so the address label is contained in a `<div>` - not sure if this should be picked up elsewhere, since geo is used in multiple content types (directories at least)?

**Comment by msayoung** [comment]
Yep as @danchamp says, I think you've already met the requirement but, since we're here...
a bit of space around the map too please, if there's a venue provided it's pretty squashed

![image](https://user-images.githubusercontent.com/3852805/123424742-26b51600-d5b9-11eb-80c9-db70256e189e.png)

Cheers

**Comment by markconroy** [comment]
Thanks @danchamp and @msayoung All done, can one of you take a second glance please?

**Comment by msayoung** [comment]
Lovely, thanks @markconroy - @danchamp if you are happy you can move this to Reviewer approved.

**Comment by danchamp** [comment]
@markconroy Thanks, much better with some breathing room.

One final comment that may be beyond scope - the 'Provider', 'Venue', and 'Address' labels might be better marked up as headings. If not can we make them visually distinctive so they are clearly identifiable as labels for the items below them please?

**Comment by markconroy** [comment]
Thanks @danchamp 

I have those labels set as bold now. Headings would be better, but I'm going with the default markup of Drupal, so we have fewer templates to maintain.

**Comment by danchamp** [comment]
Thanks @markconroy. Moving this to Reviewer approved.
