### ISSUE TITLE
Improve CSS on tables

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_base#579]
@markconroy here's a card following this discussion about better mobile handling of tables

https://localgovdrupal.slack.com/archives/CSE44GLSE/p1722004702765609

**Comment by msayoung** [comment]
Unfortunately I think we've lost the history of conversation you linked to @willguv 

However I'd like to request that at a minimum we put a horizontal scroll on tables below a certain browser width, so that the page itself doesn't break . 

If you test this demo page: https://demo.localgovdrupal.org/test-subsite-demo-all-components/example-page-tables-and-tabs at a browser width of 256 x 320 you can see the page layout breaks. 

![image](https://github.com/user-attachments/assets/da47bb16-0eb0-4c32-b4e1-4b8b4654456e)

More ideal solutions to responsive accessible tables are explored here: https://adrianroselli.com/2017/11/a-responsive-accessible-table.html

**Comment by markconroy** [comment]
#648 Should allow us to have horizontal scroll on tables that are inserted via table field.

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
