### ISSUE TITLE
Issue from "feat: add expand/collapse icon to accordion"

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_base#626]
https://github.com/localgovdrupal/localgov_base/pull/603

One thing I spotted on the "front end" is that https://github.com/localgovdrupal/localgov_base/pull/603 adds icons as expected, however this adds them to all sites _**even**_ if they have overwritten the Twig template to introduce their own icons:
![image](https://github.com/user-attachments/assets/269f0bc7-f3c8-49d8-a0d8-0c52f91031e3)
Whilst the addition of the icons is good I don't think it is wise that these are added in using JavaScript (we also add the button using this method too) - I have a PR (https://github.com/localgovdrupal/localgov_paragraphs/pull/200) that @ctorgalson has reviewed and approved which moves the creation of the button and the addition of the icons into the Twig template which I think should be released along with localgov_base v1.7.0

_Originally posted by @AWearring in https://github.com/localgovdrupal/localgov_base/issues/622#issuecomment-2376518036_

**Comment by ekes** [comment]
@markconroy @ctorgalson Do we want to resolve this before pushing https://github.com/localgovdrupal/localgov_base/pull/622 out the door?

**Comment by ctorgalson** [comment]
So _my_ TL;DR is I don't understand what difference it makes in what order they're deployed.

## Details

I'm not very well-informed about v1.7.0, but localgovdrupal/localgov_paragraphs#200 still looks fine to me as long as everyone's aware of those minor potential side effects noted in the PR.

Regarding the base issue:

> One thing I spotted on the "front end" is that https://github.com/localgovdrupal/localgov_base/pull/603 adds icons as expected, however this adds them to all sites even if they have overwritten the Twig template to introduce their own icons:

 The paragraphs change deom localgovdrupal/localgov_paragraphs#200 won't prevent that. 
 
 Unless I'm overlooking something fairly large, there are only three ways that that _could_ be prevented:
 
 1. don't render the icons in `localgov_accordion` Twig _or_ javascript,
 2. provide an identical or more specific `:after` selector in a child theme to override [`localgov_base`'s new css](https://github.com/localgovdrupal/localgov_base/pull/603/files#diff-9909c1e18bdb0186e5b4738c775fcb0fab54b0a2149ffd1e793d7b405f5d2b06R27-R33)
 3. ensure, in a child theme, that the `<button>` element in accordion panes doesn't _match_ the selector in `localgov_base`'s new css
 
The changes in localgovdrupal/localgov_paragraphs#200 don't do any of these things: they duplicate the previous markup via Twig instead of js, and address the side-effects that creates in the accordion javascript.

**Comment by finnlewis** [comment]
@AWearring suggests that maybe this is OK, with release notes to let people know that we're adding icons, so if they already have icons, they might need to override our template.

@markconroy also keen to cover this in release notes.

**Comment by ekes** [comment]
1.7.0 is out
