### ISSUE TITLE
Theme refactor frontend: Directories

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_base#9]
- [x ] Put the templates in place in the theme
- [ x] Move styling into localgov_base theme.
- [ x] confirm feature parity 

- Directory Channel - http://localgov.dev.mark.ie/localgov-drupal-collaborators
- Directory Venu - http://localgov.dev.mark.ie/localgov-drupal-collaborators/annertech
- Directory Page - http://localgov.dev.mark.ie/adult-health-and-social-care/money-employment-and-training-directory/love-food-hate-waste

**Comment by markconroy** [comment]
PR: https://github.com/localgovdrupal/localgov_base/pull/56

- Directory Page
- Directory Venue
- Directory Channel
- Facets in sidebar

Will need a class of `lgd-teaser-list` added to the `/admin/structure/views/view/localgov_directory_channel/edit/node_embed` view

**Comment by msayoung** [comment]
Looks good @markconroy 
The following issues exist on the current theme so can move these into different issues if you prefer, but: 

- On the Facets in the sidebar, the check boxes aren't keyboard accessible - we should be able to use the Space key to check

- On a Directory Page, could there be a visually heirarchy between the Enquiries fieldset label and the field labels below it? (eg http://localgov.dev.mark.ie/adult-health-and-social-care/money-employment-and-training-directory/citizens-advice )
-  On a Directory Venue, I'd like a little more visual distinction between the fields within the Enquiries fieldset. Perhaps following whatever pattern you use on the Directory Page. 

Certainly for another issue, but @danchamp have you done any a11y testing on the map on the Directory channel page?

**Comment by danchamp** [comment]
>  On the Facets in the sidebar, the check boxes aren't keyboard accessible - we should be able to use the Space key to check

@msayoung I can't replicate this and checkboxes work as expected with keyboard for me in Firefox and Edge.

@markconroy Can we highlight the checkbox and associated label on focus, and add some hover styling too please? The yellow border solely on the checkbox on focus is a bit subtle currently (see https://beta.londoncouncils.gov.uk/ for reference).

>  On a Directory Page, could there be a visually heirarchy between the Enquiries fieldset label and the field labels below it? (eg http://localgov.dev.mark.ie/adult-health-and-social-care/money-employment-and-training-directory/citizens-advice )

Should this even be a `<fieldset>` since it's not in a form? I've not seen it used like that before. The structure of the content is more akin to a definition/description list since it's in key/value pairs, so maybe use a `<dl>`?

>  On a Directory Venue, I'd like a little more visual distinction between the fields within the Enquiries fieldset. Perhaps following whatever pattern you use on the Directory Page.

Agreed these should be consistent.

> Certainly for another issue, but @danchamp have you done any a11y testing on the map on the Directory channel page?

Not yet, a full run through for a11y issues is on my list, including some screen reader testing. (I haven't reviewed this issue properly yet either.)

**Comment by markconroy** [comment]
I have all of these items updated now, except "should the address be in a fieldset". I think that should not be part of this issue, as the fieldset output is coming from the address module rather than our custom code.

@danchamp and @msayoung can you have another quick look and close this issue if everything is okay?

**Comment by msayoung** [comment]
I'm happy, and I've hunted down the Browser Extension that was messing with the keyboard accessibility. Win.
@danchamp move this on if you are happy.

**Comment by danchamp** [comment]
Thanks @markconroy @msayoung, this looks good to me and we can pick up the fieldset issue in localgov_geo
