### ISSUE TITLE
News article <time> renders full news_date field with surrounding <div>

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_base#97]
Only localgov_news_date field value should be rendered to ensure valid HTML:

https://github.com/localgovdrupal/localgov_base/blob/65bcca8af8a4bb1529217ea12223b7e089055829/templates/content/node--localgov-news-article--full.html.twig#L89-L91

**Comment by markconroy** [comment]
Hi @danchamp 

What's the issue with a `div` rendering inside a `time` element? As `div` is semantic-less, I would have thought it was okay.

I want to render the full field so we can have site builder configure the date format in the CMS, instead of the theme being opinionated about it.

I guess we could just edit the date field for the news content type to remove all the wrapper stuff and leave just `{{ item.content }}` being printed.

**Comment by danchamp** [comment]
The HTML spec restricts its permitted content phrasing content, so no flow content like `<div>`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

`<span>` as a field wrapper would be fine and would still allow the date format to be configured in the CMS - is that doable?

**Comment by markconroy** [comment]
Thanks @danchamp 

I have this fixed in #104 now
